import os
import re
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.append(str(project_root))

try:
    from tabs._styling import get_shiny_css
except ImportError as e:
    print(f"❌ Error: Could not import get_shiny_css. {e}")
    sys.exit(1)


def generate_static_css():
    print("🎨 Generating static CSS from tabs._styling.py...")

    # Get the Style Tag object
    style_tag = get_shiny_css()

    # Convert Tag to string -> <style>...css...</style>
    raw_html = str(style_tag)

    # Extract content inside <style> tags
    match = re.search(r"<style.*?>(.*?)</style>", raw_html, re.DOTALL)

    if not match:
        print("❌ Error: Could not extract CSS content.")
        # Fallback: ถ้าหา tag ไม่เจอ อาจจะลอง return string ตรงๆ ดู (เผื่ออนาคตแก้ function)
        print("Debug Raw Output:", raw_html[:100])
        sys.exit(1)

    css_content = match.group(1).strip()

    # Add Header Comment
    final_css = f"""/* ⚠️ DO NOT EDIT THIS FILE DIRECTLY 
   This file is auto-generated from tabs/_styling.py 
   Run 'python utils/update_css.py' to update.
*/

{css_content}
"""

    # Output Path
    output_path = project_root / "static" / "styles.css"
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(final_css)

    print(f"✅ Success! Static CSS saved to: {output_path}")


if __name__ == "__main__":
    generate_static_css()
