# .github/actions/setup-test-env/action.yml
name: 'Setup Test Environment'
description: 'Install common dependencies for styling tests'
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        # Install shiny to enable tabs/_common.py imports
        pip install pytest pandas numpy shiny
