# .github/actions/setup-test-env/action.yml
name: 'Setup Test Environment'
description: 'Install common dependencies for styling and verification tests'
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pytest pandas>=2.0 numpy>=1.24 shiny>=0.6
        pip install scipy>=1.10 lifelines>=0.29 scikit-learn>=1.3 
