# .github/actions/setup-test-env/action.yml
name: 'Setup Test Environment'
description: 'Install common dependencies for styling and verification tests'
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        
        # Install all dependencies from requirements.txt
        # This includes Core, Stats, Visualization, and Testing tools (pytest, etc.)
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "⚠️ requirements.txt not found! Installing minimal dependencies..."
          pip install pytest pandas numpy shiny requests scipy lifelines scikit-learn statsmodels plotly
        fi
